Repository Kuadrant/docs.kuadrant.io, pull requests merged in 2023-09, with the labels that each got.

#12 476 - MGC docs re-org
  .gitignore
  mkdocs.yml
Labels: do-not-merge/hold, lgtm

#16 Updating nav
  README.md
  docs/getting-started.md
  docs/index.md
  mkdocs.yml
Labels: lgtm, approved

#17 Updating Rate Limiting ref to point at CRD doc. Also promoted some of the Kuadrant Operator how-to guides to the top-level nav.
  mkdocs.yml
Labels: lgtm, approved

#19 update getting started
  docs/getting-started.md
Labels: lgtm, approved

#20 update to specify account and user permissions for created root domain
  docs/getting-started.md
Labels: lgtm, approved

#22 Fixing #560 - removing ref to MGC_SUB_DOMAIN (only used in a single g…
  docs/getting-started.md
Labels: lgtm

#24 Test PR for Prow
  README.md
Labels: lgtm, approved

#28 Metrics federation doc removed
  mkdocs.yml
Labels: lgtm, approved
