Repository Kuadrant/docs.kuadrant.io, pull requests merged in 2024-11, with the labels that each got.

#145 Run nightly deploy
  .github/workflows/mike-redeploy.yaml
Labels: lgtm, approved

#146 Add a dockerfile, instructions to run mkdocs locally + in podman/docker
  Dockerfile
  README.md
  requirements.txt
Labels: approved

#147 refactor: move authorino specfic guides to under Authorino User Guides
  mkdocs.yml
Labels: documentation, lgtm, approved, size/small
